#ifndef SEARCH_UTILS_UNARY_H
#define SEARCH_UTILS_UNARY_H

#include "essentials.h"
#include "debug_utils.h"
#include <map>
#include <unordered_map>
#include <chrono>

// ─── ExhaustMode ─────────────────────────────────────────────────────────────
enum class ExhaustMode {
    FAST_NO_DEPTH,
    DEBUG_MODE,
    FAST_MODE
};

// ─── Generate all 4^4 = 256 unary functions ───────────────────────────────────
inline set<vector<wire>> generate_all_unary_functions() {
    set<vector<wire>> result;
    for (int a = 0; a < BASE; a++)
    for (int b = 0; b < BASE; b++)
    for (int c = 0; c < BASE; c++)
    for (int d = 0; d < BASE; d++)
        result.insert({ (wire)a, (wire)b, (wire)c, (wire)d });
    return result;
}

// ─── unary_exhaust ────────────────────────────────────────────────────────────
// Given a binary gate Arb, repeatedly compose unary functions of the form
//   h(x) = Arb(f(x), g(x))
// starting from the seed set {identity, Arb(x,x), [constants]}.
//
// Returns {found_count, delta_count} where:
//   found_count  = how many functions from search_list were generated
//   delta_count  = how many constant (delta) unary functions were generated
//
// In base 4:
//   Total unary functions = 256 → full generation means found_count == 256
//   Constant unary funcs  = 4   → full delta means delta_count == 4
//
template<typename ArbFunc>
pair<size_t, size_t> unary_exhaust(
    ArbFunc Arb,
    ExhaustMode mode           = ExhaustMode::FAST_MODE,
    bool constant_basis        = true,
    set<vector<wire>> search_list = {})
{
    if (search_list.empty())
        search_list = generate_all_unary_functions();

    set<vector<wire>> found_set;
    size_t found_count = 0;
    size_t delta_count = 0;

    const bool DEBUG = (mode == ExhaustMode::DEBUG_MODE);

    // ── Seed functions ────────────────────────────────────────────────────────
    auto UnX  = [](wire a)    -> wire { return a; };
    auto Un1  = [Arb](wire a) -> wire { return Arb(a, a); };
    auto UnC0 = [](wire a)    -> wire { return W0; };
    auto UnC1 = [](wire a)    -> wire { return W1; };
    auto UnC2 = [](wire a)    -> wire { return W2; };
    auto UnC3 = [](wire a)    -> wire { return W3; };

    // ── DEBUG mode ────────────────────────────────────────────────────────────
    if (DEBUG) {
        printf("\nArb Matrix:\n");
        print_matrix(Arb);
        printf("\n");

        map<vector<wire>, string> S;

        S[get_vector(UnX)]  = "x";
        S[get_vector(Un1)]  = "Arb(x,x)";
        if (constant_basis) {
            S[get_vector(UnC0)] = "c0";
            S[get_vector(UnC1)] = "c1";
            S[get_vector(UnC2)] = "c2";
            S[get_vector(UnC3)] = "c3";
        }

        for (const auto& [v, expr] : S) {
            if (is_delta(v)) {
                delta_count++;
                printf("DELTA FOUND IN SEEDS!\n");
                print_vector(v);
                printf("  Generated by: %s\n", expr.c_str());
            }
            if (search_list.count(v) && !found_set.count(v)) {
                found_set.insert(v);
                found_count++;
            }
        }

        bool changed = true;
        while (changed) {
            changed = false;
            vector<pair<vector<wire>, string>> current(S.begin(), S.end());

            for (const auto& [v1, e1] : current)
            for (const auto& [v2, e2] : current) {
                auto h = compose(v1, v2, Arb);

                if (S.find(h) == S.end()) {
                    string expr = "Arb(" + e1 + ", " + e2 + ")";
                    S[h] = expr;
                    changed = true;

                    if (is_delta(h)) {
                        delta_count++;
                        printf("DELTA FOUND IN COMPOSITE!\n");
                        print_vector(h);
                        printf("  Generated by: %s\n", expr.c_str());
                    }
                    if (search_list.count(h) && !found_set.count(h)) {
                        found_set.insert(h);
                        found_count++;
                    }
                }
            }
        }

        printf("\n========================================\n");
        printf("Total unary functions generated: %zu / %d\n", S.size(), UNARY_COUNT);
        printf("Total delta (constant) funcs:    %zu / %d\n", delta_count, DELTA_COUNT);
        printf("========================================\n\n");

        return { found_set.size(), delta_count };
    }

    // ── FAST modes ────────────────────────────────────────────────────────────
    else {
        set<vector<wire>> S;

        S.insert(get_vector(UnX));
        S.insert(get_vector(Un1));
        if (constant_basis) {
            S.insert(get_vector(UnC0));
            S.insert(get_vector(UnC1));
            S.insert(get_vector(UnC2));
            S.insert(get_vector(UnC3));
        }

        for (const auto& v : S) {
            if (is_delta(v)) delta_count++;
            if (search_list.count(v) && !found_set.count(v)) {
                found_set.insert(v);
                found_count++;
            }
        }

        bool changed = true;
        while (changed) {
            changed = false;
            vector<vector<wire>> current(S.begin(), S.end());

            for (const auto& f : current)
            for (const auto& g : current) {
                vector<wire> h(BASE);
                for (int i = 0; i < BASE; i++)
                    h[i] = Arb(f[i], g[i]);

                if (search_list.count(h) && !found_set.count(h)) {
                    found_set.insert(h);
                    found_count++;
                }

                if (S.insert(h).second) {
                    if (is_delta(h)) delta_count++;
                    changed = true;
                }
            }
        }

        return { found_set.size(), delta_count };
    }
}

#endif // SEARCH_UTILS_UNARY_H
