#ifndef SEARCH_UTILS_UNARY_H
#define SEARCH_UTILS_UNARY_H

#include "essentials.h"
#include "debug_utils.h"
#include <map>
#include <unordered_map>
#include <chrono>

// ─── ExhaustMode ─────────────────────────────────────────────────────────────
enum class ExhaustMode {
    FAST_NO_DEPTH,   // set-based, no depth tracking
    DEBUG_MODE,      // map-based with expression strings + prints
    FAST_MODE        // map-based with depth, no prints
};

// ─── Generate all 2^2 = 4 unary functions ────────────────────────────────────
inline set<vector<wire>> generate_all_unary_functions() {
    set<vector<wire>> result;
    for (int i = 0; i < 2; i++)
    for (int j = 0; j < 2; j++)
        result.insert({ (wire)i, (wire)j });
    return result;
}

// ─── unary_exhaust ────────────────────────────────────────────────────────────
// Given a binary gate Arb, repeatedly compose unary functions of the form
//   h(x) = Arb(f(x), g(x))
// starting from the seed set {identity, Arb(x,x), [constants]}.
//
// Returns {found_count, delta_count} where:
//   found_count  = how many functions from search_list were generated
//   delta_count  = how many constant (delta) unary functions were generated
//
// In binary:
//   Total unary functions = 4  → full generation means found_count == 4
//   Constant unary funcs  = 2  → full delta means delta_count == 2
//
template<typename ArbFunc>
pair<size_t, size_t> unary_exhaust(
    ArbFunc Arb,
    ExhaustMode mode      = ExhaustMode::FAST_MODE,
    bool constant_basis   = true,
    set<vector<wire>> search_list = {})
{
    if (search_list.empty())
        search_list = generate_all_unary_functions();

    set<vector<wire>> found_set;
    size_t found_count = 0;
    size_t delta_count = 0;

    const bool DEBUG = (mode == ExhaustMode::DEBUG_MODE);

    // ── Seed functions ────────────────────────────────────────────────────────
    // UnX  : identity             x → x
    // Un1  : diagonal projection  x → Arb(x,x)
    // UnN/P: constants            x → F / x → T
    auto UnX = [](wire a)       -> wire { return a; };
    auto Un1 = [Arb](wire a)    -> wire { return Arb(a, a); };
    auto UnF = [](wire a)       -> wire { return T_FALSE; };
    auto UnT = [](wire a)       -> wire { return T_TRUE;  };

    // ── DEBUG mode ────────────────────────────────────────────────────────────
    if (DEBUG) {
        if (DEBUG) {
            printf("\nArb Matrix:\n");
            print_matrix(Arb);
            printf("\n");
        }

        map<vector<wire>, string> S;

        S[get_vector(UnX)] = "x";
        S[get_vector(Un1)] = "Arb(x,x)";
        if (constant_basis) {
            S[get_vector(UnF)] = "F";
            S[get_vector(UnT)] = "T";
        }

        // Check seeds
        for (const auto& [v, expr] : S) {
            if (is_delta(v)) {
                delta_count++;
                printf("DELTA FOUND IN SEEDS!\n");
                print_vector(v);
                printf("  Generated by: %s\n", expr.c_str());
            }
            if (search_list.count(v) && !found_set.count(v)) {
                found_set.insert(v);
                found_count++;
            }
        }

        bool changed = true;
        while (changed) {
            changed = false;
            vector<pair<vector<wire>, string>> current(S.begin(), S.end());

            for (const auto& [v1, e1] : current)
            for (const auto& [v2, e2] : current) {
                auto h = compose(v1, v2, Arb);

                if (S.find(h) == S.end()) {
                    string expr = "Arb(" + e1 + ", " + e2 + ")";
                    S[h] = expr;
                    changed = true;

                    if (is_delta(h)) {
                        delta_count++;
                        printf("DELTA FOUND IN COMPOSITE!\n");
                        print_vector(h);
                        printf("  Generated by: %s\n", expr.c_str());
                    }
                    if (search_list.count(h) && !found_set.count(h)) {
                        found_set.insert(h);
                        found_count++;
                    }
                }
            }
        }

        printf("\n========================================\n");
        printf("Total unary functions generated: %zu / 4\n", S.size());
        printf("Total delta (constant) funcs:    %zu / 2\n", delta_count);
        printf("========================================\n\n");

        return { found_set.size(), delta_count };
    }

    // ── FAST modes ────────────────────────────────────────────────────────────
    else {
        set<vector<wire>> S;

        S.insert(get_vector(UnX));
        S.insert(get_vector(Un1));
        if (constant_basis) {
            S.insert(get_vector(UnF));
            S.insert(get_vector(UnT));
        }

        for (const auto& v : S) {
            if (is_delta(v)) delta_count++;
            if (search_list.count(v) && !found_set.count(v)) {
                found_set.insert(v);
                found_count++;
            }
        }

        bool changed = true;
        while (changed) {
            changed = false;
            vector<vector<wire>> current(S.begin(), S.end());

            for (const auto& f : current)
            for (const auto& g : current) {
                vector<wire> h(2);
                for (int i = 0; i < 2; i++)
                    h[i] = Arb(f[i], g[i]);

                if (search_list.count(h) && !found_set.count(h)) {
                    found_set.insert(h);
                    found_count++;
                }

                if (S.insert(h).second) {
                    if (is_delta(h)) delta_count++;
                    changed = true;
                }
            }
        }

        return { found_set.size(), delta_count };
    }
}

#endif // SEARCH_UTILS_UNARY_H