#ifndef UNARY_SEARCH_H
#define UNARY_SEARCH_H

#include <iostream>
#include <set>
#include <unordered_set>
#include <vector>
#include <array>
#include <map>
#include <chrono>

enum class ExhaustMode {
    FAST_NO_DEPTH,
    DEBUG_MODE,
    FAST_MODE
};

static int unary_checks = 0;

set<vector<wire>> generate_all_unary_functions(){
    set<vector<wire>> result;
    for (size_t i=0; i < 3; i++)
    for (size_t j=0; j < 3; j++)
    for (size_t k=0; k < 3; k++){
        result.insert({(wire)i, (wire)j, (wire)k});
    }
    return result;
}

struct VectorHash
{
    size_t operator()(const vector<wire>& v) const{
        size_t h = 0;
        for (auto x : v)
            h = h * 3 + (int)x;
        return h;
    }
};


unordered_set<vector<wire>,VectorHash> unary_exhaust(
    vector<wire> Arb,
    ExhaustMode mode = ExhaustMode::FAST_MODE,
    set<vector<wire>> search_list = {})
{
    if(search_list.empty())
        search_list = generate_all_unary_functions();
    unordered_set<vector<wire>, VectorHash> found_set;
    size_t found_count = 0;
    const bool DEBUG = (mode == ExhaustMode::DEBUG_MODE);

    if (DEBUG) {
        printf("\nArb Matrix:\n");
        print_matrix(Arb);
        printf("\n");
    }
    
    
    auto UnX = [Arb](wire a){ return a; };
    auto Un1 = [Arb](wire a){ return Arb[4*a]; };

    auto start = chrono::high_resolution_clock::now();
    unary_checks++;
    if (DEBUG) {

        map<vector<wire>, string> S;

        S[get_vector(UnX)]  = "x";
        S[get_vector(Un1)]  = "Arb(x,x)";

        for (const auto& p : S) {
            print_vector(p.first);
            printf("\nGenerated by:\n\t%s\n", p.second.c_str());
            if(search_list.count(p.first) && !found_set.count(p.first)){
                found_set.insert(p.first);
                found_count++;
            }
            if(found_count >= search_list.size())
                break;
        }

        bool changed = true;

        while (changed) {
            changed = false;

            vector<pair<vector<wire>, string>> current(S.begin(), S.end());

            for (const auto& p1 : current) {
                for (const auto& p2 : current) {

                    auto h = compose(p1.first, p2.first, Arb);

                    if (S.find(h) == S.end()) {

                        string expr =
                            "Arb(" + p1.second + ", " + p2.second + ")";

                        S[h] = expr;
                        changed = true;

                        print_vector(h);
                        printf("\nGenerated by:\n\t%s\n",
                                expr.c_str());
                    }
                    if(search_list.count(h) && !found_set.count(h)){
                        found_set.insert(h);
                        found_count++;
                    }
                    if(found_count >= search_list.size())
                        break;
                }
            }
        }

        auto end = chrono::high_resolution_clock::now();
        auto duration =
            chrono::duration_cast<chrono::microseconds>(end - start);

        printf("\n========================================\n");
        printf("Total unary functions generated: %zu / 27\n",
               S.size());
        printf("Execution time: %ld microseconds\n",
               duration.count());
        printf("========================================\n\n");

        return found_set;
    }

    else { // FAST_MODE
        unordered_set<vector<wire>,VectorHash> S;

        S.insert(get_vector(UnX));
        S.insert(get_vector(Un1));

        for (const auto& v : S){
            if(search_list.count(v) && !found_set.count(v)){
                found_set.insert(v);
                found_count++;
            }
            if(found_count >= search_list.size())
                break;

        }

        bool changed = true;

        while (changed) {
            changed = false;

            vector<vector<wire>> current(S.begin(), S.end());


            for (const auto& f : current) {
                for (const auto& g : current) {
                    vector<wire> h = compose(f, g, Arb);

                    if (found_count >= search_list.size()) return found_set;  // break both loops

                    bool is = S.insert(h).second;

                    if (search_list.count(h) && !found_set.count(h)) {
                        found_set.insert(h);
                        found_count++;
                    }

                    if (is) changed = true;

                }
            }
        }
        return found_set;
    }
}

#endif