#ifndef SEARCH_UTILS_H
#define SEARCH_UTILS_H

#include <iostream>
#include <set>
#include <vector>
#include <array>
#include <map>
#include <chrono>

enum class ExhaustMode {
    FAST_NO_DEPTH,
    DEBUG_MODE,
    FAST_MODE
};

set<vector<wire>> generate_all_unary_functions(){
    set<vector<wire>> result;
    for (size_t i=0; i < 3; i++)
    for (size_t j=0; j < 3; j++)
    for (size_t k=0; k < 3; k++){
        result.insert({(wire)i, (wire)j, (wire)k});
    }
    return result;
}


template<typename ArbFunc>
pair<size_t,size_t> unary_exhaust(
    ArbFunc Arb,
    ExhaustMode mode = ExhaustMode::FAST_MODE,
    bool constant_basis = true,
    set<vector<wire>> search_list = {})
{
    if(search_list.empty())
        search_list = generate_all_unary_functions();
    
    set<vector<wire>> found_set;
    size_t found_count = 0;
    const bool DEBUG = (mode == ExhaustMode::DEBUG_MODE);

    if (DEBUG) {
        printf("\nArb Matrix:\n");
        print_matrix(Arb);
        printf("\n");
    }
    
    
    auto UnX = [Arb](wire a){ return a; };
    auto Un1 = [Arb](wire a){ return Arb(a,a); };
    auto UnN = [Arb](wire a){ return T_NEG; };
    auto UnZ = [Arb](wire a){ return T_ZERO; };
    auto UnP = [Arb](wire a){ return T_POS; };
    // auto Un11 = [Arb](wire a){ return Arb(a,T_NEG); };
    // auto Un12 = [Arb](wire a){ return Arb(a,T_ZERO); };
    // auto Un13 = [Arb](wire a){ return Arb(a,T_POS); };
    // auto Un21 = [Arb](wire a){ return Arb(T_NEG,a); };
    // auto Un22 = [Arb](wire a){ return Arb(T_ZERO,a); };
    // auto Un23 = [Arb](wire a){ return Arb(T_POS,a); };

    size_t delta_count = 0;

    auto start = chrono::high_resolution_clock::now();

    if (DEBUG) {

        map<vector<wire>, string> S;

        S[get_vector(UnX)]  = "x";
        S[get_vector(Un1)]  = "Arb(x,x)";
        if (constant_basis) {
            S[get_vector(UnN)]  = "-"; // constant -1
            S[get_vector(UnZ)]  = "0"; // constant 0
            S[get_vector(UnP)]  = "+"; // constant +1
        }
        // if(constant_basis){
        //     S[get_vector(Un11)] = "Arb(x,-)";
        //     S[get_vector(Un12)] = "Arb(x,0)";
        //     S[get_vector(Un13)] = "Arb(x,+)";
        //     S[get_vector(Un21)] = "Arb(-,x)";
        //     S[get_vector(Un22)] = "Arb(0,x)";
        //     S[get_vector(Un23)] = "Arb(+,x)";
        // }

        for (const auto& p : S) {
            if (is_delta(p.first)) {
                delta_count++;
            }
            print_vector(p.first);
            printf("\nGenerated by:\n\t%s\n", p.second.c_str());
            if(search_list.count(p.first) && !found_set.count(p.first)){
                found_set.insert(p.first);
                found_count++;
            }
            if(found_count >= search_list.size())
                break;
        }

        bool changed = true;

        while (changed) {
            changed = false;

            vector<pair<vector<wire>, string>> current(S.begin(), S.end());

            for (const auto& p1 : current) {
                for (const auto& p2 : current) {

                    auto h = compose(p1.first, p2.first, Arb);

                    if (S.find(h) == S.end()) {

                        string expr =
                            "Arb(" + p1.second + ", " + p2.second + ")";

                        S[h] = expr;
                        changed = true;

                        if (is_delta(h)) {
                            delta_count++;
                        }
                        print_vector(h);
                        printf("\nGenerated by:\n\t%s\n",
                                expr.c_str());
                    }
                    if(search_list.count(h) && !found_set.count(h)){
                        found_set.insert(h);
                        found_count++;
                    }
                    if(found_count >= search_list.size())
                        break;
                }
            }
        }

        auto end = chrono::high_resolution_clock::now();
        auto duration =
            chrono::duration_cast<chrono::microseconds>(end - start);

        printf("\n========================================\n");
        printf("Total unary functions generated: %zu / 27\n",
               S.size());
        printf("Total delta functions found:     %zu / 3\n",
               delta_count);
        printf("Execution time: %ld microseconds\n",
               duration.count());
        printf("========================================\n\n");

        return {found_set.size(), delta_count};
    }

    else { // FAST_MODE

        set<vector<wire>> S;

        S.insert(get_vector(UnX));
        S.insert(get_vector(Un1));
        if (constant_basis) {
            S.insert(get_vector(UnN));
            S.insert(get_vector(UnZ));
            S.insert(get_vector(UnP));
        }
        // if(constant_basis){
        //     S.insert(get_vector(Un11));
        //     S.insert(get_vector(Un12));
        //     S.insert(get_vector(Un13));
        //     S.insert(get_vector(Un21));
        //     S.insert(get_vector(Un22));
        //     S.insert(get_vector(Un23));
        // }

        for (const auto& v : S){
            if (is_delta(v))
                delta_count++;

            if(search_list.count(v) && !found_set.count(v)){
                found_set.insert(v);
                found_count++;
            }
            if(found_count >= search_list.size())
                break;

        }

        bool changed = true;

        while (changed) {
            changed = false;

            vector<vector<wire>> current(S.begin(), S.end());

            for (const auto& f : current) {
                for (const auto& g : current) {

                    vector<wire> h(3);
                    for (int i = 0; i < 3; i++)
                        h[i] = Arb(f[i], g[i]);

                    if(search_list.count(h) && !found_set.count(h)){
                        found_set.insert(h);
                        found_count++;
                    }

                    if (S.insert(h).second) {

                        if (is_delta(h))
                            delta_count++;

                        changed = true;
                    }
                }
            }
        }
        return {found_set.size(), delta_count};
    }
}

#endif